// <auto-generated />
using System;
using JobSearcher.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace JobSearcher.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260417190345_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("JobSearcher.Models.Companies", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CompanyAppliedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("CompanyCallOrNot")
                        .HasColumnType("integer");

                    b.Property<string>("CompanyContactPerson")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("CompanyJobLink")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("CompanyLocation")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("CompanyMinorNotes")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("CompanyName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("CompanyPosition")
                        .HasColumnType("integer");

                    b.Property<int>("CompanyStatus")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CompanyTopOfMind")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CompanyWebsite")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Companies");
                });
#pragma warning restore 612, 618
        }
    }
}
